DROP TABLE Audit_Logs;

CREATE TABLE Audit_Logs (
 LogID INT IDENTITY(1,1) PRIMARY KEY,
 TableName VARCHAR(50),
 Action VARCHAR(10),
 OldData NVARCHAR(MAX),
 NewData NVARCHAR(MAX),
 ChangedBy VARCHAR(100) DEFAULT SYSTEM_USER,
 ChangedAt DATETIME DEFAULT GETDATE()
);